name: simple_nba
description: Simple NBA scoreboard

dependencies:
  http: "^0.11.3+16"
  image: "^1.1.29"
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Mono
      fonts:
      - asset: assets/MonoFont.ttf

  assets:
    - assets/DET.png
    - assets/MIN.png
    - assets/POR.png
    - assets/GSW.png
    - assets/TOR.png
    - assets/CLE.png
    - assets/BOS.png
    - assets/PHI.png
    - assets/LAL.png
    - assets/ATL.png
    - assets/ORL.png
    - assets/MEM.png
    - assets/HOU.png
    - assets/BKN.png
    - assets/MIL.png
    - assets/NYK.png
    - assets/WAS.png
    - assets/OKC.png
    - assets/PHX.png
    - assets/DAL.png
    - assets/UTA.png
    - assets/SAS.png
    - assets/CHI.png
    - assets/NOP.png
    - assets/MIA.png
    - assets/IND.png
    - assets/SAC.png
    - assets/DEN.png
    - assets/CHA.png
    - assets/NBA.png
    - assets/LAC.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages


